# Generated by Django 4.2 on 2024-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['balance'], name='accounts_ac_balance_3b70f6_idx'),
        ),
    ]
